# Generated by Django 2.2.6 on 2020-02-25 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200225_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_invest', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.ExpenseType')),
                ('user_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.UserBill')),
            ],
        ),
    ]
