# Generated by Django 2.2.6 on 2020-02-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_expense_expensetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbill',
            name='attendance_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbill',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
