# Generated by Django 2.2.10 on 2020-02-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20200227_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbill',
            old_name='total',
            new_name='food_sum',
        ),
    ]
