# Generated by Django 2.2.10 on 2020-02-27 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20200227_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbill',
            old_name='carry_over',
            new_name='credit',
        ),
    ]
