# Generated by Django 2.2.10 on 2020-02-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20200227_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbill',
            name='calculation_factor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
    ]
