# Generated by Django 2.2.10 on 2020-02-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_userbill_calculation_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='expense_types',
            field=models.ManyToManyField(to='food.ExpenseType'),
        ),
    ]
