# Generated by Django 2.2.10 on 2020-02-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_bill_expense_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbill',
            name='expense_types',
            field=models.ManyToManyField(to='food.ExpenseType'),
        ),
    ]
