# Generated by Django 2.2.10 on 2020-02-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_userbill_expense_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbill',
            name='expense_types',
        ),
    ]
