# Generated by Django 2.2.10 on 2020-03-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_auto_20200304_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total_attendance_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
