# Generated by Django 2.2.10 on 2020-03-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_bill_total_attendance_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='total_food',
            new_name='total_supermarket',
        ),
        migrations.AddField(
            model_name='bill',
            name='total_terra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
