# Generated by Django 2.2.10 on 2020-03-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_auto_20200304_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='days_in_month',
            field=models.PositiveIntegerField(editable=False, verbose_name='Days/Mo'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='terra_daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Terra Rate'),
        ),
    ]
