# Generated by Django 2.2.10 on 2020-03-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_auto_20200304_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbill',
            name='invest_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_attendance_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Days'),
        ),
    ]
