# Generated by Django 2.2.10 on 2020-03-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_auto_20200305_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
