# Generated by Django 2.2.11 on 2020-03-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0020_bill_is_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbill',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Januar'), (2, 'Februar'), (3, 'März'), (4, 'April'), (5, 'Mai'), (6, 'Juni'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'December')]),
        ),
        migrations.AlterField(
            model_name='userbill',
            name='food_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='userbill',
            name='invest_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='userbill',
            name='luxury_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
