# Generated by Django 2.2.11 on 2020-03-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_auto_20200305_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbill',
            name='is_notified',
        ),
        migrations.AddField(
            model_name='userbill',
            name='expense_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='userbill',
            name='calculation_factor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Calc. factor'),
        ),
    ]
