# Generated by Django 2.2.11 on 2020-04-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0022_auto_20200329_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbill',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbill',
            name='calculation_factor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Calcf.'),
        ),
        migrations.AlterField(
            model_name='userbill',
            name='has_payed',
            field=models.BooleanField(default=False, verbose_name='Payed?'),
        ),
    ]
