# Generated by Django 2.2.11 on 2020-05-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0025_inventory_terrainvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terrainvoice',
            old_name='deposit',
            new_name='deposit_sum',
        ),
    ]
