# Generated by Django 2.2.11 on 2020-06-20 13:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0027_auto_20200619_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inventory_food_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('luxus_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('terra_brutto_all_sum', models.DecimalField(blank=True, decimal_places=2, help_text='Sum of all brutto terra invoice totals', max_digits=8, null=True)),
                ('terra_food_others_sum', models.DecimalField(blank=True, decimal_places=2, help_text='Sum of all terra invoices without deposit and not from pumpwerk', max_digits=8, null=True)),
                ('attendance_day_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('corrected_terra_daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['-inventory__created'],
            },
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-bill_date'], 'verbose_name': 'Bill'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-created'], 'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='userbill',
            options={'ordering': ['-bill__bill_date'], 'verbose_name': 'User Bill'},
        ),
        migrations.RemoveField(
            model_name='userbill',
            name='has_payed',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='bills',
            field=models.ManyToManyField(to='food.Bill'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sum_luxury',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbill',
            name='has_paid',
            field=models.BooleanField(default=False, verbose_name='Paid?'),
        ),
        migrations.AlterField(
            model_name='terrainvoice',
            name='is_pumpwerk',
            field=models.BooleanField(default=True, verbose_name='Is pumpwerk order?'),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='UserPayback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('has_paid', models.BooleanField(default=False, verbose_name='Paid?')),
                ('comment', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User payback',
                'verbose_name_plural': 'User paybacks',
                'ordering': ['-account__from_month', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('payment_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bills', models.ManyToManyField(to='food.TerraInvoice')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='food.Inventory'),
        ),
    ]
