# Generated by Django 2.2.11 on 2020-06-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0029_auto_20200620_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-inventory_date'], 'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='created',
            new_name='inventory_date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='when',
            new_name='payment_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='month',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='year',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='month',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='year',
        ),
    ]
