# Generated by Django 2.2.11 on 2020-06-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0032_auto_20200620_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terrainvoice',
            options={'ordering': ['-terra_invoice_date'], 'verbose_name': 'Terra Invoice', 'verbose_name_plural': 'Terra Invoices'},
        ),
        migrations.RenameField(
            model_name='terrainvoice',
            old_name='date',
            new_name='terra_invoice_date',
        ),
    ]
