# Generated by Django 2.2.11 on 2020-06-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0033_auto_20200620_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='luxus_sum',
            new_name='luxury_sum',
        ),
    ]
