# Generated by Django 2.2.11 on 2020-06-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0034_auto_20200620_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_food_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
