# Generated by Django 2.2.11 on 2020-06-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0035_account_total_food_expenses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='total_food_expenses',
            new_name='total_food_pumpwerk_expenses',
        ),
        migrations.AddField(
            model_name='account',
            name='terra_brutto_others_sum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sum of all terra invoices without deposit and not from pumpwerk', max_digits=8, null=True),
        ),
    ]
