# Generated by Django 2.2.11 on 2020-06-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0036_auto_20200620_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='luxury_sum',
            new_name='consumed_luxury',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='total_food_pumpwerk_expenses',
            new_name='food_expenses_pumpwerk_sum',
        ),
        migrations.AddField(
            model_name='account',
            name='luxury_paid_diff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Lux paid diff'),
        ),
        migrations.AddField(
            model_name='account',
            name='terra_deposit_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Deposit bal.'),
        ),
        migrations.AddField(
            model_name='account',
            name='terra_food_pumpwerk_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='terra_luxury_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='additional_inventory_food',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Add. inv. food'),
        ),
        migrations.AlterField(
            model_name='account',
            name='attendance_day_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tot. days'),
        ),
        migrations.AlterField(
            model_name='account',
            name='corrected_terra_daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='New Terra rate'),
        ),
        migrations.AlterField(
            model_name='account',
            name='terra_brutto_all_sum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sum of all brutto terra invoice totals', max_digits=8, null=True, verbose_name='Tot. Terra brutto (all)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='terra_food_others_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tot. food (others)'),
        ),
    ]
