# Generated by Django 2.2.11 on 2020-06-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0037_auto_20200621_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='consumed_luxury',
            new_name='luxury_consumed',
        ),
        migrations.AlterField(
            model_name='account',
            name='food_expenses_pumpwerk_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tot. food (PW)'),
        ),
    ]
