# Generated by Django 2.2.11 on 2020-06-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0039_auto_20200622_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='terra_daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='The terra rate used in the bills.'),
            preserve_default=False,
        ),
    ]
