# Generated by Django 2.2.11 on 2020-06-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0040_inventory_terra_daily_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='terra_daily_rate',
        ),
        migrations.AddField(
            model_name='account',
            name='previous_terra_daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Prev. Terra rate'),
            preserve_default=False,
        ),
    ]
