# Generated by Django 2.2.11 on 2020-06-22 07:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0041_auto_20200622_0951'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpayback',
            unique_together={('user', 'account')},
        ),
    ]
