# Generated by Django 2.2.11 on 2020-10-08 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0042_auto_20200622_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_account', to='food.Account'),
        ),
    ]
