# Generated by Django 2.2.11 on 2020-10-08 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0044_remove_account_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='food.Account'),
        ),
    ]
