# Generated by Django 2.2.11 on 2020-10-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0045_auto_20201008_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='inventory',
            new_name='account',
        ),
    ]
