# Generated by Django 2.2.11 on 2020-10-08 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0047_auto_20201008_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='account',
        ),
        migrations.AlterField(
            model_name='account',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account', to='food.Inventory'),
        ),
    ]
