# Generated by Django 2.2.11 on 2021-02-07 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0050_auto_20210207_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_carry_over',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.Bill'),
        ),
    ]
