# Generated by Django 2.2.11 on 2021-02-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0051_bill_bill_carry_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrainvoice',
            name='luxury_sum_19',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='terrainvoice',
            name='luxury_sum_7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='terrainvoice',
            name='luxury_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
