# Generated by Django 2.2.26 on 2022-02-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0053_terrainvoice_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrainvoice',
            name='fee',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Additional fee'),
        ),
    ]
