# Generated by Django 2.2.26 on 2022-02-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0054_auto_20220213_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='terra_food_others_fee_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tot. food (others) with fee'),
        ),
        migrations.AlterField(
            model_name='terrainvoice',
            name='fee',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Fee in percentage, e.g. 1 for 1% or 2 for 2%.', null=True, verbose_name='Additional fee'),
        ),
    ]
