# Generated by Django 2.2.26 on 2022-02-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0055_auto_20220213_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='terra_food_pumpwerk_fee_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='terra_food_others_fee_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tot. food (others) + fee'),
        ),
    ]
