# Generated by Django 2.2.28 on 2024-11-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0057_auto_20220225_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-inventory__inventory_date'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='userpayback',
            options={'ordering': ['-account', 'user'], 'verbose_name': 'User payback', 'verbose_name_plural': 'User paybacks'},
        ),
        migrations.AddField(
            model_name='account',
            name='additional_inventory_luxury',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Add. inv. luxury'),
        ),
        migrations.AlterField(
            model_name='account',
            name='corrected_terra_daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='New Terra rate (+Fee)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='terra_food_pumpwerk_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Fee food (PW)'),
        ),
    ]
