# Generated by Django 2.2.28 on 2024-11-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0058_auto_20241101_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_bill_luxury_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='User bill luxury sum'),
        ),
        migrations.AlterField(
            model_name='account',
            name='additional_inventory_food',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='(self.inventory.sum_inventory - self.inventory.sum_luxury) - (previous_inventory.sum_inventory - previous_inventory.sum_luxury)', max_digits=8, null=True, verbose_name='Add. inv. food'),
        ),
        migrations.AlterField(
            model_name='account',
            name='additional_inventory_luxury',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='self.inventory.sum_luxury - previous_inventory.sum_luxury', max_digits=8, null=True, verbose_name='Add. inv. luxury'),
        ),
        migrations.AlterField(
            model_name='account',
            name='luxury_consumed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='self.terra_luxury_sum - self.additional_inventory_luxury', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='luxury_paid_diff',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='user_bill_luxury_sum + self.inventory.sum_cash - self.luxury_consumed', max_digits=8, null=True, verbose_name='Lux paid diff'),
        ),
        migrations.AlterField(
            model_name='account',
            name='terra_luxury_sum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=" terra_sums['luxury_sum'] #total luxury from terra invoices", max_digits=8, null=True),
        ),
    ]
