# Generated by Django 2.2.28 on 2024-11-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0059_auto_20241101_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='luxury_rate',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Preis pro Strich', max_digits=8, verbose_name='Luxury Rate'),
        ),
        migrations.AddField(
            model_name='userbill',
            name='luxury_count',
            field=models.PositiveIntegerField(blank=True, help_text='Anzahl der Luxusstriche', null=True),
        ),
        migrations.AlterField(
            model_name='terrainvoice',
            name='luxury_sum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='(self.luxury_sum_7 * Decimal(1.07)) + (self.luxury_sum_19 * Decimal(1.19))', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='userbill',
            name='luxury_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Luxury'),
        ),
    ]
