# Generated by Django 2.2.28 on 2024-11-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0060_auto_20241101_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='luxury_rate',
            field=models.DecimalField(decimal_places=2, help_text='Preis pro Strich', max_digits=8, verbose_name='Luxury Rate'),
        ),
    ]
