# Generated by Django 2.2.28 on 2024-11-19 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0061_auto_20241101_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayback',
            name='total_luxury_count',
            field=models.PositiveIntegerField(blank=True, help_text='Summe der Luxusstriche', null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='members',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userbill',
            name='luxury_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Anzahl der Luxusstriche * Preis pro Strich', max_digits=8, null=True, verbose_name='Luxury sum'),
        ),
    ]
