# Generated by Django 2.2.28 on 2025-01-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0062_auto_20241119_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='luxury_rate',
        ),
        migrations.RemoveField(
            model_name='userbill',
            name='luxury_count',
        ),
        migrations.RemoveField(
            model_name='userpayback',
            name='total_luxury_count',
        ),
        migrations.AddField(
            model_name='userpayback',
            name='total_luxury_sum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Summe Luxus', max_digits=8, null=True),
        ),
    ]
