# Generated by Django 2.2.28 on 2025-11-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0063_auto_20250109_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='transfer_sum_from_totals',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Supermarket + Terra + Invest + Luxury', max_digits=8, null=True, verbose_name='Transfer sum from totals'),
        ),
        migrations.AddField(
            model_name='bill',
            name='transfer_sum_from_userbills',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sum of all userbill totals', max_digits=8, null=True, verbose_name='Transfer sum from userbills'),
        ),
    ]
