# Generated by Django 2.2.28 on 2025-11-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0064_auto_20251106_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_diff',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total unpaid due to inaccurate terra rate.', max_digits=8, null=True, verbose_name='Tot. missing terra'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='transfer_sum_from_totals',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Terra + Luxury - Usercredits', max_digits=8, null=True, verbose_name='Transfer sum from totals'),
        ),
        migrations.AlterField(
            model_name='terrainvoice',
            name='luxury_sum_19',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='terrainvoice',
            name='luxury_sum_7',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
