# Generated by Django 2.2.6 on 2020-02-25 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200225_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='active_members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
