# Generated by Django 2.2.6 on 2020-02-25 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_setting_active_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Settings'},
        ),
    ]
