# Generated by Django 2.2.10 on 2020-02-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200225_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calculation_factor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
    ]
